# Generated by Django 3.2.5 on 2022-08-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lesson_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='planned_time',
            field=models.CharField(max_length=164, null=True),
        ),
    ]
