# Generated by Django 3.2.5 on 2022-08-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
